config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts

  get 'main/joinus'

  get 'main/gallery_2'

  get 'main/robotics'

  get 'main/index'

  get 'main/gallery'



    root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :debug
  #
  # def debug
  #   byebug
  # end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index

    end
    def gallery 

    end
    def gallery_2 

    end
    def robotics 

    end

   def joinus
    render :layout => false
   end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy!
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Protons</title>
  <%= csrf_meta_tags %>




  <link href="/layout/styles/layout.css" rel="stylesheet" type="text/css" media="all">
  <script src="/layout/scripts/jquery.min.js"></script>
  <script src="/layout/scripts/jquery.backtotop.js"></script>
  <script src="/layout/scripts/jquery.mobilemenu.js"></script>
</head>

<body>

<div class="wrapper row1">
  <header id="header" class="hoc clear">
    <!-- ################################################################################################ -->
    <h1><a href="index.html"><img src="http://protons.alexsb.org/media/protons-black.png" alt="Logo"></a></h1>
    <!-- ################################################################################################ -->
  </header>
</div>
<div class="wrapper row4">
  <nav id="mainav" class="hoc clear">
    <!-- ################################################################################################ -->
    <ul class="clear">
      <li class="active"><a href="/main/index">Home</a></li>
      <li><a href="/main/gallery">Gallery</a>
      </li>
      <li><a class="drop" href="#">Tracks</a>
        <ul>
          <li><a href="/main/robotics">Robotics</a></li>
          <li><a href="/main/programming"> Programming </a></li>
          <li><a href="/main/automation">Automation</a></li>
        </ul>
      </li>
      <li><a href="/main/joinus">Join Us</a></li>
    </ul>
    <!-- ################################################################################################ -->
  </nav>
</div>

<%= yield %>

<div class="wrapper row4">
  <footer id="footer" class="hoc clear">
    <!-- ################################################################################################ -->
    <div class="one_third first">
      <h6 class="heading">Find Us At</h6>
      <ul class="nospace btmspace-30 linklist contact">
        <li><i class="fa fa-map-marker"></i>
          <address>
            Faculty of Engineering Alexandria university, Electrical Engineering building ground floor <br> Alexandria,
            Egypt
          </address>
        </li>
        <li><i class="fa fa-phone"></i> (+20) 111-424-2927</li>
        <li><i class="fa fa-envelope-o"></i> info@alexsb.com</li>
      </ul>
      <ul class="faico clear">
        <li><a class="faicon-facebook" href="https://www.facebook.com/ProtonsAlexSB/"><i class="fa fa-facebook"></i></a>
        </li>
        <li><a class="faicon-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a class="faicon-dribble" href="#"><i class="fa fa-dribbble"></i></a></li>
        <li><a class="faicon-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a class="faicon-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a class="faicon-vk" href="#"><i class="fa fa-vk"></i></a></li>
      </ul>
    </div>
    <div class="one_third">
      <h6 class="heading">In faucibus orci luctus</h6>
      <ul class="nospace linklist">
        <li>
          <article>
            <h2 class="nospace font-x1"><a href="#">Ultrices posuere cubilia</a></h2>
            <time class="font-xs block btmspace-10" datetime="2045-04-06">Friday, 6<sup>th</sup> April 2045</time>
            <p class="nospace">Lorem laoreet blandit donec mollis lacinia massa tincidunt malesuada [&hellip;]</p>
          </article>
        </li>
        <li>
          <article>
            <h2 class="nospace font-x1"><a href="#">Curae cras tincidunt eros</a></h2>
            <time class="font-xs block btmspace-10" datetime="2045-04-05">Thursday, 5<sup>th</sup> April 2045</time>
            <p class="nospace">In id semper turpis in tristique dui ut ac mauris magna nunc eros enim [&hellip;]</p>
          </article>
        </li>
      </ul>
    </div>
    <div class="one_third">
      <h6 class="heading">Contact Us</h6>
      <p class="nospace btmspace-30">We are happy to receive any questions or suggestions from you.</p>
      <form method="post" action="#">
        <fieldset>
          <legend>Newsletter:</legend>
          <input class="btmspace-15" type="text" value="" placeholder="Name">
          <input class="btmspace-15" type="text" value="" placeholder="Email">
          <input class="btmspace-15" type="text" value="" placeholder="Message">
          <button type="submit" value="submit">Submit</button>
        </fieldset>
      </form>
    </div>
    <!-- ################################################################################################ -->
  </footer>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row5">
  <div id="copyright" class="hoc clear">
    <!-- ################################################################################################ -->
    <p class="fl_left">Copyright &copy; 2017 - All Rights Reserved - <a href="#">Protons</a></p>
    <p class="fl_right">Template by
      <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
    <!-- ################################################################################################ -->
  </div>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>
</body>

</html>

app/views/main/gallery.html.erb
<div class="wrapper bgded overlay" style="background-image:url('../images/demo/backgrounds/01.png');">
  <section id="breadcrumb" class="hoc clear">
    <!-- ################################################################################################ -->
    <ul>
      <li><a href="/main/index">Home</a></li>
      <li><a href="/main/gallery">Gallery</a></li>
      <li><a href="/main/gallery">Robotics Track</a></li>
    </ul>
    <!-- ################################################################################################ -->
    <h6 class="heading">Gallery</h6>
    <!-- ################################################################################################ -->
  </section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="content">

      <!-- ################################################################################################ -->
      <div id="gallery">
        <figure>
          <header class="heading"> Robotics Track (2017)</header>
          <ul class="nospace clear">
            <li class="one_quarter first"><a href="#"><img src="http://i.imgur.com/H3gyxIP.jpgg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/NmnX2E3.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/2h6fiLe.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/0sEE2uy.jpg" alt=""></a></li>
            <li class="one_quarter first"><a href="#"><img src="http://i.imgur.com/EFu7oc3.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/7GgQ6I2.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/DeXj2wf.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/3kICK0C.jpg" alt=""></a></li>
            <li class="one_quarter first"><a href="#"><img src="http://i.imgur.com/wvsTAXG.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/DSXthr5.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/us4sSZI.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/fpJCAIz.jpg" alt=""></a></li>
          </ul>

          <figcaption>For the full album, <a href="https://www.facebook.com/pg/ProtonsAlexSB/photos/?tab=album&album_id=1320339368033838">click here</a>.</figcaption>

        </figure>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <nav class="pagination">
        <ul>
          <li><a href="#">&laquo; Previous</a></li>
          <li class="current"><strong>1</strong></li>

          <li><a href="/main/gallery_2">2</a></li>
          <li><a href="/main/gallery_3">3</a></li>
          <li><a href="/main/gallery_4">4</a></li>
          <li><a href="/main/gallery_2">Next &raquo;</a></li>

        </ul>
      </nav>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>

app/views/main/gallery_2.html.erb
<div class="wrapper bgded overlay" style="background-image:url('../images/demo/backgrounds/01.png');">

  <section id="breadcrumb" class="hoc clear">
    <!-- ################################################################################################ -->
    <ul>
      <li><a href="/main/index">Home</a></li>
      <li><a href="/main/gallery">Gallery</a></li>
      <li><a href="/main/gallery_2">Programming Track</a></li>

    </ul>
    <!-- ################################################################################################ -->
    <h6 class="heading">Gallery</h6>
    <!-- ################################################################################################ -->
  </section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">

  <main class="hoc container clear">
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="content">

      <!-- ################################################################################################ -->
      <div id="gallery">
        <figure>
          <header class="heading"> Programming Track (2017)</header>
          <ul class="nospace clear">
            <li class="one_quarter first"><a href="#"><img src="http://i.imgur.com/5jb7V0k.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/OWI1ARS.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/ZplIScD.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/JepM8JG.jpg" alt=""></a></li>
            <li class="one_quarter first"><a href="#"><img src="http://i.imgur.com/KCERyn4.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/PuDaPp3.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/aNsD6LT.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/leSdITp.jpg" alt=""></a></li>
            <li class="one_quarter first"><a href="#"><img src="http://i.imgur.com/n3Bsr79.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/2ehfuXA.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/kVcPziI.jpg" alt=""></a></li>
            <li class="one_quarter"><a href="#"><img src="http://i.imgur.com/Q7xmocq.jpg" alt=""></a></li>
          </ul>

          <figcaption>For the full album, <a href="https://www.facebook.com/pg/ProtonsAlexSB/photos/?tab=album&album_id=1318876181513490">click here</a>. </figcaption>

        </figure>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <nav class="pagination">
        <ul>

          <li><a href="/main.gallery">&laquo; Previous</a></li>
          <li><a href="/main/gallery">1</a></li>
          <li class="current"><strong>2</strong></li>
          <li><a href="/main/gallery_2">3</a></li>
          <li><a href="/main/gallery_4">4</a></li>
          <li><a href="/main/gallery_3">Next &raquo;</a></li>

        </ul>
      </nav>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>

</div>

app/views/main/joinus.html.erb
<html>
<style>
  body {
    background-color: #A8A8A8;
    font-family: 'Roboto', sans-serif;
  }

  .container-joinus {
    /*border:1px solid white;*/
    width: 600px;
    height: 350px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    display: inline-flex;
  }

  .backbox {
    background-color: #404040;
    width: 100%;
    height: 80%;
    position: absolute;
    transform: translate(0, -50%);
    top: 50%;
    display: inline-flex;
  }

  .frontbox {
    background-color: white;
    border-radius: 20px;
    height: 100%;
    width: 50%;
    z-index: 10;
    position: absolute;
    right: 0;
    margin-right: 3%;
    margin-left: 3%;
    transition: right .8s ease-in-out;
  }

  .moving {
    right: 45%;
  }

  .loginMsg, .signupMsg {
    width: 50%;
    height: 100%;
    font-size: 15px;
    box-sizing: border-box;
  }

  .loginMsg .title,
  .signupMsg .title {
    font-weight: 300;
    font-size: 23px;
  }

  .loginMsg p,
  .signupMsg p {
    font-weight: 100;
  }

  .textcontent {
    color: white;
    margin-top: 65px;
    margin-left: 12%;
  }

  .loginMsg button,
  .signupMsg button {
    background-color: #404040;
    border: 2px solid white;
    border-radius: 10px;
    color: white;
    font-size: 12px;
    box-sizing: content-box;
    font-weight: 300;
    padding: 10px;
    margin-top: 20px;
  }

  /* front box content*/
  .login, .signup {
    padding: 20px;
    text-align: center;
  }

  .login h2,
  .signup h2 {
    color: #558eff;
    font-size: 22px;
  }

  .inputbox {
    margin-top: 30px;
  }

  .login input,
  .signup input {
    display: block;
    width: 100%;
    height: 40px;
    background-color: #f2f2f2;
    border: none;
    margin-bottom: 20px;
    font-size: 12px;
  }

  .login button,
  .signup button {
    background-color: #558eff;
    border: none;
    color: white;
    font-size: 12px;
    font-weight: 300;
    box-sizing: content-box;
    padding: 10px;
    border-radius: 10px;
    width: 60px;
    position: absolute;
    right: 30px;
    bottom: 30px;
    cursor: pointer;
  }

  /* Fade In & Out*/
  .login p {
    cursor: pointer;
    color: #404040;
    font-size: 15px;
  }

  .loginMsg, .signupMsg {
    /*opacity: 1;*/
    transition: opacity .8s ease-in-out;
  }

  .visibility {
    opacity: 0;
  }

  .hide {
    display: none;
  }

</style>


<body>
<div class="container-joinus">
  <div class="backbox">
    <div class="loginMsg">
      <div class="textcontent">
        <p class="title">Don't have an account?</p>
        <p>Sign up to join the Protons team</p>
        <button id="switch1">Sign Up</button>
        <a href="/main/index"><button id="switch1">Back to Home</button></a>
      </div>
    </div>
    <div class="signupMsg visibility">
      <div class="textcontent">
        <p class="title">Have an account?</p>
        <p>Log in to get back to your profile.</p>
        <button id="switch2">LOG IN</button>
        <a href="/main/index"><button id="switch2">Back to Home</button></a>
      </div>
    </div>
  </div>
  <!-- backbox -->

  <div class="frontbox">
    <div class="login">
      <h2>LOG IN</h2>
      <%= form_tag session_path(User) do%>
          <div class="form-group">
            <input type="text" name="email" placeholder="  EMAIL">
            <input type="password" name="password" placeholder="  PASSWORD">
          </div>
          <%= submit_tag "log in"%>
      <% end %>
    </div>

    <div class="signup hide">
      <h2>SIGN UP</h2>
      <div class="inputbox">
        <%= form_tag registration_path(User), method: :post do%>
            <div class="form-group">
              <input type="text" name="email" placeholder="  EMAIL">
              <input type="password" name="password" placeholder="  PASSWORD">
            </div>
            <%= submit_tag "sign up"%>
        <% end %>
      </div>
    </div>

  </div>
  <!-- frontbox -->
</div>
</body>
<script
src="http://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<script src="js/bootstap.js"></script>
<script>
    var $loginMsg = $('.loginMsg'),
        $login = $('.login'),
        $signupMsg = $('.signupMsg'),
        $signup = $('.signup'),
        $frontbox = $('.frontbox');

    $('#switch1').on('click', function () {
        $loginMsg.toggleClass("visibility");
        $frontbox.addClass("moving");
        $signupMsg.toggleClass("visibility");

        $signup.toggleClass('hide');
        $login.toggleClass('hide');
    })

    $('#switch2').on('click', function () {
        $loginMsg.toggleClass("visibility");
        $frontbox.removeClass("moving");
        $signupMsg.toggleClass("visibility");

        $signup.toggleClass('hide');
        $login.toggleClass('hide');
    })

    setTimeout(function () {
        $('#switch1').click()
    }, 1000)

    setTimeout(function () {
        $('#switch2').click()
    }, 3000)</script>
</html>

app/views/main/robotics.html.erb
<div class="wrapper bgded overlay" style="background-image:url('../images/demo/backgrounds/01.png');">
  <section id="breadcrumb" class="hoc clear">
    <!-- ################################################################################################ -->
    <ul>
      <li><a href="index.html">Home</a></li>
      <li><a href="#">Tracks</a></li>
      <li><a href="robotics.html">Robotics</a></li>
    </ul>
    <!-- ################################################################################################ -->
    <h6 class="heading">Robotics Track</h6>
    <!-- ################################################################################################ -->
  </section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="content">

      <!-- ################################################################################################ -->
      <h1>Welcome to the world of Robotics</h1>
      <img class="imgr borderedbox inspace-5" src="http://kino.putc.org/_ld/0/79437141.jpg" alt="">
      <p>Think about it for a moment, robots now do nearly everything that humans can and cannot do. From building cars to washing dishes, robots are now everywhere. The problem, however, is that all these tasks are programmed by humans; we tell robots what to do; they are our servants.</p>
      <p>But, will robots one day break free of their human bosses, rebel, unite, and make a plan to desroy mankind? Or maybe flip things around and make us their servants.</p>
      <p>Let's get this funny thought away and focus on what we'll learn at Protons to understand robots before they understand us.</p>
      <p>As a proton, you will learn:  </p>

      <ul class="fa-ul">
        <li><i class="fa-li fa fa-wrench"></i> Mechanics in robot design</li>
        <li><i class="fa-li fa fa-wrench"></i> CAD: Use Solidworks to design your robot and other bodies </li>
        <li><i class="fa-li fa fa-wrench"></i> Prototyping Electronics: Learn how to use both the simple breadboards and the more durable PCBs to model and design your circuits. </li>
        <li><i class="fa-li fa fa-wrench"></i> Motors and Drivers</li>
        <li><i class="fa-li fa fa-wrench"></i>Arduino and C Programming</li>
        <li><i class="fa-li fa fa-wrench"></i> <p>Microcontroller I/O : Learn about Digital and analog input/output usage and applications.</p> </li>
        <li><i class="fa-li fa fa-wrench"></i> Prototyping Electronics: Learn how to use both the simple breadboards and the more durable PCBs to model and design your circuits. </li>
      </ul>
      <p>Portortornec condimenterdum eget consectetuer condis consequam pretium pellus sed mauris enim. Puruselit mauris nulla hendimentesque elit semper nam a sapien urna sempus.</p>
      <div class="container-article">

        <div class="column">
          <!-- Post-->
          <div class="post-module">
            <!-- Thumbnail-->
            <a href="https://www.livescience.com/59802-should-we-fear-intelligent-robots.html" >
              <div class="thumbnail">
                <div class="date">
                  <div class="day">14</div>
                  <div class="month">Jul</div>
                </div><img src="https://img.purch.com/h/1400/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzA5My84MzEvb3JpZ2luYWwvcm9ib3QtYXJteS5qcGc="/>
              </div>
              <!-- Pos  t Content-->
              <div class="post-content">
                <div class="category">Robots</div>
                <h1 class="title">Should We Fear The Rise of Intelligent Robots? </h1>
                <h2 class="sub_title"> Robots will unite. </h2>
                <p class="description"></p>
              </div>
            </a>
          </div>
        </div>
      </div>

      <div id="comments">
        <h2>Comments</h2>
        <ul>
          <li>
            <article>
              <header>
                <figure class="avatar"><img src="../images/demo/avatar.png" alt=""></figure>
                <address>

                  By <a href="#">A Name</a>

                </address>
                <time datetime="2045-04-06T08:15+00:00">Friday, 6<sup>th</sup> April 2045 @08:15:00</time>
              </header>
              <div class="comcont">
                <p>This is an example of a comment made on a post. You can either edit the comment, delete the comment or reply to the comment. Use this as a place to respond to the post or to share what you are thinking.</p>
              </div>
            </article>
          </li>
          <li>
            <article>
              <header>
                <figure class="avatar"><img src="../images/demo/avatar.png" alt=""></figure>
                <address>

                  By <a href="#">A Name</a>

                </address>
                <time datetime="2045-04-06T08:15+00:00">Friday, 6<sup>th</sup> April 2045 @08:15:00</time>
              </header>
              <div class="comcont">
                <p>This is an example of a comment made on a post. You can either edit the comment, delete the comment or reply to the comment. Use this as a place to respond to the post or to share what you are thinking.</p>
              </div>
            </article>
          </li>
          <li>
            <article>
              <header>
                <figure class="avatar"><img src="../images/demo/avatar.png" alt=""></figure>
                <address>

                  By <a href="#">A Name</a>

                </address>
                <time datetime="2045-04-06T08:15+00:00">Friday, 6<sup>th</sup> April 2045 @08:15:00</time>
              </header>
              <div class="comcont">
                <p>This is an example of a comment made on a post. You can either edit the comment, delete the comment or reply to the comment. Use this as a place to respond to the post or to share what you are thinking.</p>
              </div>
            </article>
          </li>
        </ul>
        <h2>Write A Comment</h2>
        <form action="#" method="post">
          <div class="one_third first">
            <label for="name">Name <span>*</span></label>
            <input type="text" name="name" id="name" value="" size="22" required>
          </div>
          <div class="one_third">
            <label for="email">Mail <span>*</span></label>
            <input type="email" name="email" id="email" value="" size="22" required>
          </div>
          <div class="one_third">
            <label for="url">Website</label>
            <input type="url" name="url" id="url" value="" size="22">
          </div>
          <div class="block clear">
            <label for="comment">Your Comment</label>
            <textarea name="comment" id="comment" cols="25" rows="10"></textarea>
          </div>
          <div>
            <input type="submit" name="submit" value="Submit Form">
            &nbsp;
            <input type="reset" name="reset" value="Reset Form">
          </div>
        </form>
      </div>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post, method: :get %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= button_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<article>
  <header>
    <figure class="avatar"><img src="../images/demo/avatar.png" alt=""></figure>
    <address>

      <%= @post.title %>

    </address>
    <time datetime="2045-04-06T08:15+00:00">Friday, 6<sup>th</sup> April 2045 @08:15:00</time>
  </header>
  <div class="comcont">
    <p><%= @post.content %> </p>
  </div>
</article>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>